
[[weapons.defs]]
  name = "2chains_1"
  props = "whip"
  x = 50.0
  y = -60.0
[[weapons.defs]]
  name = "2chains_2"
  props = "whip"
  x = 50.0
  y = -70.0

[[chains]]
  object1 = "player"
  object2 = "2chains_1"
  x = 50.0
  y = -60.0
  length = 10

[[chains]]
  object1 = "player"
  object2 = "2chains_2"
  x = 50.0
  y = -70.0
  length = 20
