
[[weapons.defs]]
    x = 50.0
    y = -63.0
    name = "cat_little1"
    props = "cat"

[[weapons.defs]]
  x = 53.0
  y = -66.0
  name = "cat_little2"
  props = "cat"

[[weapons.defs]]
  x = 47.0
  y = -63.0
  name = "cat_little3"
  props = "cat"

[[weapons.defs]]
  x = 50.0
  y = -60.0
  name = "cat_ball"
  props = "joiner"

[[chains]]
  object1 = "player"
  object2 = "cat_ball"
  x = 50.0
  y = -50.0
  length = 12

[[chains]]
  object1 = "cat_ball"
  object2 = "cat_little1"
  x = 50.0
  y = -50.0
  length = 3
[[chains]]
  object1 = "cat_ball"
  object2 = "cat_little2"
  x = 50.0
  y = -50.0
  length = 6
[[chains]]
  object1 = "cat_ball"
  object2 = "cat_little3"
  x = 50.0
  y = -50.0
  length = 9
