[chasers.props]
  linear_damping = 1.5
  scale = 0.5
  density = 0.01
  restitution = 0.4

[[chasers.defs]]
  x = 80.0
  y = -50.0
[[chasers.defs]]
  x = 80.0
  y = -20.0
[[chaers.defs]]
  x = 80.0
  y = -80.0
