[chasers.props]
  linear_damping = 1.5
  scale = 0.5
  density = 2.0
  restitution = 0.4

[[chasers.defs]]
  x = 80.0
  y = -50.0
[[chasers.defs]]
  x = 80.0
  y = -20.0
[[chasers.named_defs]]
  name = "armed_chaser"
  def = {x = 80.0, y = -80.0}

[[weapons]]
  class = "noob_whip"
  root = "armed_chaser"

[[weapons]]
  class = "long_chain_2"
  root = "player"
