[chasers.props]
  linear_damping = 1.5
  scale = 0.5
  density = 0.01
  restitution = 0.2

[[chasers.defs]]
  x = 80.0
  y = -50.0
[[chasers.defs]]
  x = 80.0
  y = -20.0
[[chasers.named_defs]]
  name = "armed_chaser"
  def = {x = 80.0, y = -80.0}

[[weapons]]
  class = "noob_whip"
  root = "armed_chaser"

[[weapons]]
  class = "2chains"
  root = "player"

[[weapons]]
  class ="big_whip"
  root = "player"

[[weapons]]
  class ="cat_of_nine"
  root = "player"

[[weapons]]
  class ="deadblow"
  root = "player"

[[weapons]]
  class ="long_chain"
  root = "player"

[[weapons]]
  class ="name_collision"
  root = "player"

[[weapons]]
  class ="noob_whip"
  root = "player"

[[weapons]]
  class ="rebound"
  root = "player"

[[weapons]]
  class ="whip"
  root = "player"
