
[weapons.props.whip]
  linear_damping = 0.5
  angular_damping = 0.1
  scale = 0.25
  density = 4.0
  restitution = 0.4

[weapons.props.deadblow]
  linear_damping = 0.5
  angular_damping = 0.1
  scale = 0.25
  density = 4.0
  restitution = -1.0

[weapons.props.rebound]
  linear_damping = 0.5
  angular_damping = 0.1
  scale = 0.25
  density = 4.0
  restitution = 0.8

[weapons.props.little]
  linear_damping = 0.5
  angular_damping = 0.1
  scale = 0.15
  density = 1.0
  restitution = 0.8

[weapons.props.joiner]
  linear_damping = 0.5
  angular_damping = 0.1
  scale = 0.15
  density = 0.2
  restitution = 0.8

[weapons.props.cat]
  linear_damping = 0.5
  angular_damping = 0.1
  scale = 0.15
  density = 0.5
  restitution = 0.2

[weapons.props.big]
  linear_damping = 0.5
  angular_damping = 0.1
  scale = 0.35
  density = 6.0
  restitution = 0.0
