name = "2chains"

[[colliders]]
  name = "2chains_1"
  props = "whip"
  x = 0.0
  y = -10.0
[[colliders]]
  name = "2chains_2"
  props = "whip"
  x = 0.0
  y = -10.0

[[chains]]
  object1 = "root"
  object2 = "2chains_1"
  x = 0.0
  y = -10.0
  length = 10

[[chains]]
  object1 = "root"
  object2 = "2chains_2"
  x = 0.0
  y = -10.0
  length = 20
